<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.BakhZdE' shared service.

return $this->privates['.service_locator.BakhZdE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\BlogController::delete' => ['privates', '.service_locator.7R7ZrzG', 'get_ServiceLocator_7R7ZrzGService.php', true],
    'App\\Controller\\BlogController::dioxma' => ['privates', '.service_locator.7R7ZrzG', 'get_ServiceLocator_7R7ZrzGService.php', true],
    'App\\Controller\\BlogController::trouver' => ['privates', '.service_locator.7R7ZrzG', 'get_ServiceLocator_7R7ZrzGService.php', true],
    'App\\Controller\\BlogController:delete' => ['privates', '.service_locator.7R7ZrzG', 'get_ServiceLocator_7R7ZrzGService.php', true],
    'App\\Controller\\BlogController:dioxma' => ['privates', '.service_locator.7R7ZrzG', 'get_ServiceLocator_7R7ZrzGService.php', true],
    'App\\Controller\\BlogController:trouver' => ['privates', '.service_locator.7R7ZrzG', 'get_ServiceLocator_7R7ZrzGService.php', true],
], [
    'App\\Controller\\BlogController::delete' => '?',
    'App\\Controller\\BlogController::dioxma' => '?',
    'App\\Controller\\BlogController::trouver' => '?',
    'App\\Controller\\BlogController:delete' => '?',
    'App\\Controller\\BlogController:dioxma' => '?',
    'App\\Controller\\BlogController:trouver' => '?',
]);
