<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.7R7ZrzG' shared service.

return $this->privates['.service_locator.7R7ZrzG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'post' => ['privates', '.errored..service_locator.7R7ZrzG.App\\Entity\\BlogPost', NULL, 'Cannot autowire service ".service_locator.7R7ZrzG": it references class "App\\Entity\\BlogPost" but no such service exists.'],
], [
    'post' => 'App\\Entity\\BlogPost',
]);
